apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - image: docker.io/sobczykm/url-shortener:v2
        name: url-shortener
        ports:
        - containerPort: 3000