apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-shortener
  namespace: url-shortener
spec:
  destination:
    name: url-shortener
    namespace: url-shortener
    server: https://kubernetes.default.svc
  source:
    path: ./go-app
    repoURL: https://github.com/sobczykm/helm-charts
    targetRevision: main
    helm:
      parameters:
        - name: image.tag
          value: v2
        - name: image.repository
          value: sobczykm/url-shortener
      valueFiles: []
      values: |
        replicaCount: 1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true